#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from enum import Enum
from klip_model import KlipModel
import argparse
import klip_common


DESCRIPTION = '''
Utility to manage clippings from Kindle.'''


class UIMode(Enum):
    GUI = 0
    CMD = 2


DEFAULT_MODE = UIMode.GUI


parser = argparse.ArgumentParser(description=DESCRIPTION)
parser.add_argument('--gui', dest='ui', action='store_const',
                    const=UIMode.GUI, default=DEFAULT_MODE,
                    help='specify UI to use')
parser.add_argument('--cmd', dest='ui', action='store_const',
                    const=UIMode.CMD, default=DEFAULT_MODE,
                    help='specify UI to use')
parser.add_argument('--debug', dest='debug', action='store_true',
                    default=False,
                    help='turn on debug mode')


if __name__ == '__main__':

    m = KlipModel()
    args = parser.parse_args()

    if args.debug:
        klip_common.debug_mode = True
    else:
        klip_common.debug_mode = False

    if args.ui == UIMode.CMD:
        from klip_cmd import startCMD
        startCMD(m)
    elif args.ui == UIMode.GUI:
        from klip_gui import startGUI
        startGUI(m)
    else:
        print('oops.')
